- path: "/"
  methods: 
  - method: GET
    headers:
      contentType: json/xml
    response:
      contentType: json/xml
      file: file.json
      statusCode: 200
  - method: POST
    headers:
      contentType: json/xml
    response:
      contentType: json/xml
      file: file.json
      statusCode: 200
- path: "/api"
  methods: 
  - method: POST
    headers:
      contentType: json/xml
    response:
      contentType: json/xml
      file: file.json
      statusCode: 200
